apiVersion: cloud.google.com/v1beta1
kind: BackendConfig
metadata:
  name: api-backend
  namespace: final-space
spec:
  connectionDraining:
    drainingTimeoutSec: 60
  sessionAffinity:
    affinityType: "CLIENT_IP"
