apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: prod-api-ingress
  namespace: final-space
  annotations:
    kubernetes.io/ingress.global-static-ip-name: prod-v2-api-ip
    networking.gke.io/managed-certificates: prod-api-certificate
    nginx.org/websocket-services: "api"
spec:
  backend:
    serviceName: api
    servicePort: 80
