apiVersion: v1
kind: Service
metadata:
  name: api
  labels:
    application: api
    component: api
  namespace: final-space
spec:
  type: LoadBalancer
  sessionAffinity: ClientIP
  ports:
  - port: 80
    protocol: TCP
    targetPort: 9000
  selector:
    application: api
    component: api
