apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: final-space
  labels:
    application: api
    component: redis
    type: single
spec:
  ports:
    - port: 6379
      protocol: TCP
      targetPort: 6379
  selector:
    application: api
    component: redis
    type: single
